version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
jobs:
  build_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t senouis/libertymedia-frontend .
workflows:
  version: 2
  build_and_push:
    jobs:
      - build_docker_image